# -*- coding: utf-8 -*-
"""Exercise1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PoGLYYoqoeP4vDUQcFlF82VIpdgkNqTa

Create a 5X2 random integer array and Prints its attributes • The shape of an array • Array dimensions • The length of each elements of an array in bytes
"""

import numpy as np
a = np.random.randint(0,10,size=(5,2))
np.shape(a)

a.ndim

a.nbytes

"""Create a 4X2 random integer array from a range between 10 to 20 such that the difference between each element is 2."""

np.arange(10,20,2)

"""Create a 6X4 random integer array and print the following"""

b= np.random.randint(10,size=(6,4))
b

"""• The third column"""

b[:,2]

"""• Array of odd rows and even columns"""

b[[1,3,5]]

b[:,[1,2,]]

"""• Array of square of each element"""

np.square(b)

"""Split the array into two equal sub arrays"""

np.split(b,b[2])

"""• Sort the array by the second row"""

np.sort(b,axis=0)

"""• Sort the array by the second column"""

np.sort(b,axis= 1)

"""• Amax from axis 0 and Amin from axis 1"""

np.max(b,axis=0)

np.min(b,axis=0)

"""• Delete column 2 and insert [1,2,3,4,5,6] to column 2"""

np.delete(b,b[:,1])
b[:,1]= [1,2,3,4,5,6]
b

"""• Rotate by 90 degree"""

np.rot90(b)

"""• Print the most frequent value in the array"""

print(np.bincount(b).argmax())

"""• Flatten the array to 1D"""

b.flatten()

"""• Replace values less than 10 by a NAN."""

b[b < 10] = 5

""" Summarize the array statistically (mean,mode,median, ¼ -quartile, ¾-quartile,max,min)"""

np.mean(b)

np.percentile(b, 0.75)

np.percentile(b, 3.75)

np.max(b)

np.min(b)